### ISSUE TITLE
Add standard likelihood methods

### ISSUE THREAD

**Issue by nicholasmalaya** [libqueso/queso#196]
Add gaussian likelihood evaluations to queso. We certainly like that QUESO permits the user to pass a likelihood in, but adding a few generic, commonly used functions would permit avoiding reinventing the wheel constantly.

**Comment by dmcdougall** [comment]
See #312, #319, #321, #322, #323.

**Comment by dmcdougall** [comment]
> See #312, #319, #321, #322, #323.

All of these have been merged now.  Closing.
