### ISSUE TITLE
GammaVectorRV constructor runtime error that should be compile time  

### ISSUE THREAD

**Issue by eRite** [libqueso/queso#212]
As you long as we're on the subject of constructors...
Have a look at the GammaVectorRV C file. The constructor takes in a reference to a VectorSet and then immediately dynamic casts it into a BoxSubset. This caught me with some strange errors when I first upgraded my old QUESO code to the new version. I had to look through the source code to figure out why. A lot of people who use QUESO are not going to be able/want to look through the QUESO source to figure that out, if they have the misfortune of passing an actual VectorSet to GammaVectorRV. The most obvious fix is just to change the constructor to take a BoxSubset reference so no dynamic_cast is necessary. I don't know if that is the best solution, but I would say that this should definitely be a compile time error, not runtime when the dynamic_cast fails.

**Comment by dmcdougall** [comment]
Fixed in #230.
