### ISSUE TITLE
User-defined matlab code as likelihood function

### ISSUE THREAD

**Issue by darkangel123** [libqueso/queso#263]
Is it possible to incorporate a matlab code or a black-box simulation (complex QoI function evaluation) into likelihood.C for QUESO?

**Comment by dmcdougall** [comment]
@eRite Thanks for supplying these useful resources.

I'm going to close this since it seems the question is answered.

@darkangel123 If you feel it hasn't been answered, feel free to re-open this ticket.  If you'd like to ask more specific questions, feel free to open a new ticket.
