### ISSUE TITLE
Make the c-style likelihood data routine take a void * so we can pass extra foo to queso we might need

### ISSUE THREAD

**Issue by dmcdougall** [libqueso/queso#283]

**Comment by dmcdougall** [comment]
This appears to already be the case: http://libqueso.com/queso/v0.56.1/html/a00123.html#a4619abc294e9703b564b4c034211f078

The function pointer `double(*)(const V &domainVector, const V *domainDirection, const void *routinesDataPtr, V *gradVector, M *hessianMatrix, V *hessianEffect)` takes a `const void *` so the user can pass in arbitrary foo it might need for a likelihood evaluation.

Closing.

**Comment by briadam** [comment]
Darn, wish I had noticed that existed when updating Dakota's QUESO interface a while back.  I'll move soon to C++ specialization anyway, but good to know that's there.
