### ISSUE TITLE
Move `BaseEnvironment::allOptionsMap` into an intermediary-boost-options parser class

### ISSUE THREAD

**Issue by dmcdougall** [libqueso/queso#358]

**Comment by dmcdougall** [comment]
First mentioned [here](https://github.com/libqueso/queso/pull/352#issuecomment-97785604).

**Comment by dmcdougall** [comment]
The `allOptionsMap` is protected in `BaseEnvironment`.  I'm okay with removing this and absorbing it into an intermediary Boost options parser class because I don't expect the user to subclass `BaseEnvironment` to create their own custom queso environment.

Sound reasonable?

**Comment by pbauman** [comment]
:+1: 

I'm still puzzled why there's even a base class to begin with. There's a "Full" version and an "Empty" version. Who would ever use an "Empty" environment?

**Comment by dmcdougall** [comment]
I don't know.  Perhaps we can deprecate the subclasses and rename `BaseEnvironment` to `FullEnvironment`.

**Comment by pbauman** [comment]
I'd leave it as is. Who knows what the future holds.

**Comment by dmcdougall** [comment]
#376 is merged, so I'm closing this.
