### ISSUE TITLE
where is the newest PDF user manual or how to make it?

### ISSUE THREAD

**Issue by andyyuan78** [libqueso/queso#396]

**Comment by dmcdougall** [comment]
Admittedly, we haven't done the best job at keeping the manual up to date.  You can find an instantiation of the manual [here](https://github.com/libqueso/queso/blob/dev/QUESO_users_manual.pdf).

Fortunately, I was asked to contribute a chapter on QUESO to the Springer Handbook on Uncertainty Quantification.  It's shorter than the manual, but is targeted towards the same audience.  You can download it [here](http://arxiv.org/abs/1507.00398).

Hope that helps.

**Comment by dmcdougall** [comment]
I forgot to mention that if you want to build the manual yourself, you can `cd` to the `manual` directory and type `make`.  You'll need a LaTeX distribution and you'll need `dia` installed to do this.

If you've more specific questions about queso, I encourage you to email the users mailing list `queso-users@googlegroups.com`.

I'll close this ticket now, but feel free to re-open it if I haven't answered your question.
