### ISSUE TITLE
Fix memory leaks in GPMSAFactory

### ISSUE THREAD

**Issue by dmcdougall** [libqueso/queso#399]
[Here](https://github.com/libqueso/queso/blob/dev/src/gp/src/GPMSA.C#L555) we do a bunch of heap allocations and they're not `delete`d anywhere.

**Comment by roystgnr** [comment]
I'm handling this in my multivariate branch, if you want to let it lie until that's ready to merge.

**Comment by dmcdougall** [comment]
Works for me.  Thanks for sorting that out.

**Comment by dmcdougall** [comment]
And sorry for my terrible programming.
