### ISSUE TITLE
uqGslVector test seg fault

### ISSUE THREAD

**Issue by briadam** [libqueso/queso#405]
On my RHEL6 build, test_uqGslVector seg faults because the env is deleted before the destructors for the VectorSpace objects are called (and the VS destructor refers to env).  This can be fixed by deleting param_space before deleting env, and scoping big_param_space so it gets destroyed before the env is deleted.  I didn't propose a patch because I wasn't sure how you'd prefer to fix this...

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bd835f in QUESO::BaseEnvironment::displayVerbosity (this=0x86d9d0)
    at ../../src/core/src/Environment.C:398
398	  queso_require_msg(m_optionsObj, "m_optionsObj variable is NULL");

#0  0x00007ffff7bd835f in QUESO::BaseEnvironment::displayVerbosity (this=0x86d9d0)
    at ../../src/core/src/Environment.C:398
#1  0x00007ffff7c5b8f0 in QUESO::VectorSpace<QUESO::GslVector, QUESO::GslMatrix>::~VectorSpace (this=0x7fffffffd910, __in_chrg=<value optimized out>)
    at ../../src/basic/src/VectorSpace.C:133
#2  0x000000000040a11c in main ()

**Comment by dmcdougall** [comment]
Fixed in #406.
