### ISSUE TITLE
Add sanity check for parameter bounds in `InterpolationSurrogateDataSet`

### ISSUE THREAD

**Issue by dmcdougall** [libqueso/queso#427]
The user can give an unbounded domain (think Gaussian prior).  But doing this to build an interpolation surrogate would be bad; [this](http://libqueso.com/queso/html/a00137.html#a830f9e41a1b266a46e73bd544d9ef0c0) can be `inf`.

**Comment by pbauman** [comment]
Sorry about that. We need to add hooks to let them set the min/max bounds then in cases like this, with a sensible default (say 3 sigma for Gaussian, for example?).

**Comment by dmcdougall** [comment]
No need to apologise.  I'm actually against passing the prior random variable object to the surrogate builder, there's really no need for the surrogate to have any probabilistic information aside from the domain description.  That said, this means we need to have a think about what a 'sensible default' means.  Especially since gaussians aren't the only ones with unbounded domains.

**Comment by pbauman** [comment]
Maybe a default doesn't make sense then. Perhaps instead we just check if the bounds are +/- inf and then error out if the user hasn't set values to whatever hooks we provide.

**Comment by pbauman** [comment]
BTW, how urgent is this? I'm absolutely buried until the first week of April.

**Comment by dmcdougall** [comment]
Not at all.  I just wanted to open a ticket so I didn't forget about it or get burned by it in the near future.

**Comment by dmcdougall** [comment]
We could also do with checking for zero length domains, and making sure the number of points asked for in each dimension is at least two.
