### ISSUE TITLE
Assertions optimised out with with -O2, despite not using -DNDEBUG?

### ISSUE THREAD

**Issue by dmcdougall** [libqueso/queso#481]
See [here](https://github.com/libqueso/queso/pull/478#issuecomment-261589110) for an instance where @roystgnr's build managed to not trigger an assertion.

**Comment by roystgnr** [comment]
I don't think it was the assertion compiled out, though I think it was the value asserted changing.  I'll try testing that.

**Comment by roystgnr** [comment]
This was a red herring; a libMesh-enabled build was pulling in -DNDEBUG from those CPPFLAGS.
