### ISSUE TITLE
GCC 4.4.7 compat: typename in non-templated classes

### ISSUE THREAD

**Issue by briadam** [libqueso/queso#489]
As follow-up to #488, the following need review:

A number of SharedPtr had typename prefix in non-templated classes.  Of the remaining instances of `typename SharedPtr|ScopedPtr`, I believe the following files also need review, but I'm not building these files for Dakota, so can't edit/test.
```
src/core/src/InfiniteDimensionalMCMCSampler.C
src/core/src/LibMeshOperatorBase.C
src/core/src/LibMeshFunction.C
src/core/src/LibMeshNegativeLaplacianOperator.C
src/core/inc/InfiniteDimensionalMCMCSampler.h
src/core/inc/LibMeshFunction.h
src/core/inc/LibMeshOperatorBase.h
```
These uses appear fine (don't need review) as they are in templated classes
```
src/core/inc/Factory.h
src/gp/inc/GPMSA.h
src/stats/inc/MetropolisHastingsSG.h
src/surrogates/inc/InterpolationSurrogateIOBase.h
```

**Comment by dmcdougall** [comment]
Fixed in #492.
