### ISSUE TITLE
Consolidate configured headers

### ISSUE THREAD

**Issue by briadam** [libqueso/queso#494]
Suggested enhancement: What do you think about consolidating config_queso.h and queso.h, or at least reworking them so they each have include guards and don't redefine any duplicate pre-processor names?  

There isn't a particular bug right now, just potential for confusion, e.g., when the static configure-time generated BUILD_DATE in queso.h doesn't get overridden by the compile time one in config_queso.h.

**Comment by dmcdougall** [comment]
If I'm honest, I'm struggling to think of a reason why we needed both to begin with.

**Comment by briadam** [comment]
Okay I can do a review of which defines are actually used and propose something.  A few of the things in queso.h might not really be "configured," but probably not too much of an abuse to put in config_queso.h.

**Comment by dmcdougall** [comment]
I propose nuking the dupes in `queso.h` and adding `#include <queso_config.h>` in `queso.h` assuming `config_queso.h` is installed.

Just in case anyone is actually using `queso.h`.

**Comment by pbauman** [comment]
I would suggest throwing in a `#warning` in the deprecated header for those that are actually using the header.

**Comment by briadam** [comment]
@dmcdougall If it fits with your workflow, could the changes on libqueso:hotfix-0.56.1 be merged into dev?  I presume I should make changes to queso.h on dev? It would help to have all the typename stuff there...

**Comment by dmcdougall** [comment]
I could certainly argue that's a bug fix.  Sounds good to me.

**Comment by briadam** [comment]
Sorry I should have asked a question instead of stating something.  Which branch should my pull request be based on to resolve this issue #494?

**Comment by dmcdougall** [comment]
Branch off of `hotfix-0.56.1`.

`hotfix-0.56.1` will be merged to both `master` and `dev`.  I think once this is resolved we can do a `v0.56.1` release.  Does that sound reasonable?
