### ISSUE TITLE
Default ctor for GPMSAOptions

### ISSUE THREAD

**Issue by briadam** [libqueso/queso#505]
@roystgnr I tried to setup a GPMSA problem without an input file and ran into the issue hinted at by @dmcdougall in GPMSA.C:479.  It looks like the intention is to allow options structure, input file, or none (to get default options).  The code is correctly protecting the case of neither (none) because the GPMSAOptions() constructor taking an input prefix rightly requires an input file (else it dies).

I propose that GPMSAOptions() support a default constructor, paralleling SipOptionsValues().  Then I can default construct the options and only override those I need to through C++.

Note: in my longer-term plan to allow Dakota power users to provide a QUESO input file to set advanced options not exposed to Dakota, I'll need the current functionality, but for testing, it would be helpful to not need the input file.

**Comment by roystgnr** [comment]
I'll see what I can do.  We ought to redefine the constructor there anyway, to support delayed input file parsing, and I'll fix both issues in the same pass.

**Comment by briadam** [comment]
We discussed a need to revisit other options classes (primarily environment, inverse problem, MH algorithm) to have them all support default construct, input file construct, C++ API override, delayed input file parse modes in flexible order.
