### ISSUE TITLE
Make ConcatenatedVectorRV implementation requirements mirror those of VectorRV

### ISSUE THREAD

**Issue by briadam** [libqueso/queso#506]
The constructors for ConcatenatedVectorRV access members of the component VectorRVs that may not be implemented, resulting in runtime errors.  Relevant code is at ConcatenatedVectorRV.C:99 and following.

Suggest having the non-NULL members in ConcatentedVectorRV mirror those of a VectorRV itself.  Or if realizer is required, enforcing that.

Use case: In Dakota I construct my own QuesoVectorRV that has an image set and PDF, but no realizer.  When passing this as the prior to GPMSA it rightly gets concatenated with the hyper parameter priors, but the ConcatenatedVectorRV constructor fails at runtime as noted above.

(Per our discussion @dmcdougall @roystgnr)

**Comment by roystgnr** [comment]
So the solution here is probably to add a ```bool BaseVectorRV::has_realizer()``` and test that before trying to blindly copy a sub-RV's realizer?  Since has_realizer() wouldn't need to be virtual we could do that without breaking anybody's subclasses.
