### ISSUE TITLE
Failed compilation with --disable-boost-program-options

### ISSUE THREAD

**Issue by pbauman** [libqueso/queso#517]
Modules environment:

<pre>
[05:28:29][pbauman@fry:/fry1/data/shared/software/builddir/queso-R5Kar7/queso-0.56.1]$ module list

Currently Loaded Modules:
  1) emacs/24.4   2) autotools/1.0   3) git/2.3.0   4) valgrind/3.11.0   5) paraview/4.3.1   6) cmake/3.5.2   7) texlive/2014   8) doxygen/1.8.9.1   9) gcc/6.3.0  10) mpich/3.2  11) gsl/2.1  12) glpk/4.60  13) hdf5/1.8.18

[05:29:29][pbauman@fry:/fry1/data/shared/software/builddir/queso-R5Kar7/queso-0.56.1]$
</pre>

Result of configure:
<pre>
----------------------------------- SUMMARY -----------------------------------

Package version............... : queso-0.56.1

Debug mode.................... : no
C++ compiler.................. : mpic++
C++ compiler flags............ : -g -O2 -Wall
C Preprocessor flags.......... : -DDISABLE_BOOST_PROGRAM_OPTIONS
 
GSL_LIBS...................... : -L/fry1/data/shared/software/libs/gsl/2.1/gcc/6.3.0/lib -lgsl -lgslcblas -lm
BOOST_DIR..................... :
 
Install dir................... : /usr/local
Build user.................... : pbauman
Build host.................... : fry.eng.buffalo.edu
Configure date................ : 2017-01-13 17:28
Build architecture............ : x86_64-unknown-linux-gnu
git revision.................. : N/A

Optional Features:
   Link with MPI.............. : yes
   Link with GRVY............. : no
   Link with GLPK............. : yes
   Link with HDF5............. : no
   Link with Trilinos......... : no
   Link with libmesh.......... : no
   Enable gcov code coverage.. : no
   Build internal ANN library. : no

Optional Feature Paths:
   GLPK DIR................... : /fry1/data/shared/software/libs/glpk/4.60/gcc/6.3.0

-------------------------------------------------------------------------------
</pre>

Compilation errors:
<pre>
  CXX      core/src/EnvironmentOptions.lo
core/src/EnvironmentOptions.C: In constructor ‘QUESO::EnvOptionsValues::EnvOptionsValues(const QUESO::BaseEnvironment*, const char*)’:
core/src/EnvironmentOptions.C:149:53: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, const char [1])’
   m_help = m_env->input()(m_option_help, UQ_ENV_HELP);
                                                     ^
core/src/EnvironmentOptions.C:150:101: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, int)’
   m_numSubEnvironments = m_env->input()(m_option_numSubEnvironments, UQ_ENV_NUM_SUB_ENVIRONMENTS_ODV);
                                                                                                     ^
core/src/EnvironmentOptions.C:151:102: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, const char [2])’
   m_subDisplayFileName = m_env->input()(m_option_subDisplayFileName, UQ_ENV_SUB_DISPLAY_FILE_NAME_ODV);
                                                                                                      ^
core/src/EnvironmentOptions.C:152:102: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, int)’
   m_subDisplayAllowAll = m_env->input()(m_option_subDisplayAllowAll, UQ_ENV_SUB_DISPLAY_ALLOW_ALL_ODV);
                                                                                                      ^
core/src/EnvironmentOptions.C:153:111: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, int)’
   m_subDisplayAllowInter0 = m_env->input()(m_option_subDisplayAllowInter0, UQ_ENV_SUB_DISPLAY_ALLOW_INTER0_ODV);
                                                                                                               ^
core/src/EnvironmentOptions.C:156:37: error: invalid use of incomplete type ‘const class QUESO::GetPot’
   unsigned int size = m_env->input().vector_variable_size(m_option_subDisplayAllowedSet);
                                     ^
In file included from ../inc/queso/Miscellaneous.h:28:0,
                 from core/src/EnvironmentOptions.C:30:
../inc/queso/Environment.h:55:7: note: forward declaration of ‘class QUESO::GetPot’
 class GetPot;
       ^~~~~~
core/src/EnvironmentOptions.C:160:78: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, unsigned int&, unsigned int&)’
     unsigned int allowed = m_env->input()(m_option_subDisplayAllowedSet, i, i);
                                                                              ^
core/src/EnvironmentOptions.C:164:94: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, int)’
   m_displayVerbosity = m_env->input()(m_option_displayVerbosity, UQ_ENV_DISPLAY_VERBOSITY_ODV);
                                                                                              ^
core/src/EnvironmentOptions.C:165:85: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, int)’
   m_syncVerbosity = m_env->input()(m_option_syncVerbosity, UQ_ENV_SYNC_VERBOSITY_ODV);
                                                                                     ^
core/src/EnvironmentOptions.C:166:85: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, int)’
   m_checkingLevel = m_env->input()(m_option_checkingLevel, UQ_ENV_CHECKING_LEVEL_ODV);
                                                                                     ^
core/src/EnvironmentOptions.C:167:67: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, const char [4])’
   m_rngType = m_env->input()(m_option_rngType, UQ_ENV_RNG_TYPE_ODV);
                                                                   ^
core/src/EnvironmentOptions.C:168:57: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, int)’
   m_seed = m_env->input()(m_option_seed, UQ_ENV_SEED_ODV);
                                                         ^
core/src/EnvironmentOptions.C:169:82: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, const char [1])’
   m_platformName = m_env->input()(m_option_platformName, UQ_ENV_PLATFORM_NAME_ODV);
                                                                                  ^
core/src/EnvironmentOptions.C:170:97: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::string&, const char [1])’
   m_identifyingString = m_env->input()(m_option_identifyingString, UQ_ENV_IDENTIFYING_STRING_ODV);
                                                                                                 ^
core/src/EnvironmentOptions.C: In function ‘std::ostream& QUESO::operator<<(std::ostream&, const QUESO::EnvOptionsValues&)’:
core/src/EnvironmentOptions.C:242:21: error: invalid use of incomplete type ‘const class QUESO::GetPot’
   obj.m_env->input().print(os);
                     ^
In file included from ../inc/queso/Miscellaneous.h:28:0,
                 from core/src/EnvironmentOptions.C:30:
../inc/queso/Environment.h:55:7: note: forward declaration of ‘class QUESO::GetPot’
 class GetPot;
       ^~~~~~
make[3]: *** [core/src/EnvironmentOptions.lo] Error 1
</pre>

Sorry I don't have time to fix this myself at the moment (working on features instead), but I at least wanted to log it.

**Comment by pbauman** [comment]
Oops, forgot to include configure line sorry.

<pre>
./configure --disable-boost-program-options --without-trilinos
</pre>

And this is the 0.56.1 QUESO release.

**Comment by dmcdougall** [comment]
I've got a fix coming for this.

**Comment by pbauman** [comment]
Dammit, I don't recall what exactly I checked, but doing a pure dev build, I'm see errors now.

<pre>
../../../pbauman/src/basic/src/ScalarFunction.C: In constructor ‘QUESO::BaseScalarFunction<V, M>::BaseScalarFunction(const char*, const QUESO::VectorSet<V, M>&)’:
../../../pbauman/src/basic/src/ScalarFunction.C:74:36: error: invalid use of incomplete type ‘const class QUESO::GetPot’
   unsigned int size = m_env.input().vector_variable_size(m_prefix + "fdStepSize");
                                    ^
In file included from ../inc/queso/ScalarFunction.h:28:0,
                 from ../../../pbauman/src/basic/src/ScalarFunction.C:25:
../inc/queso/Environment.h:54:7: note: forward declaration of ‘class QUESO::GetPot’
 class GetPot;
       ^
../../../pbauman/src/basic/src/ScalarFunction.C:83:38: error: no match for call to ‘(const QUESO::GetPot) (std::__cxx11::basic_string<char>, const char [5], unsigned int&)’
                                     i);
                                      ^
</pre>

Sorry @dmcdougall
