### ISSUE TITLE
GPMSA domain and data scaling

### ISSUE THREAD

**Issue by briadam** [libqueso/queso#551]
Per discussion with @dmcdougall @roystgnr : Embed any necessary scaling of calibration / config domains and simulation (training) and experimental data into the GPMSA capability.  (Not positive any variable scaling is necessary.)

As GPMSA requires (or at least @brianw525 recommends) data be centered and scaled, either do this automatically, or provide convenience routines that the client can use to make sure the data is properly transformed.  This is helpful for scalar/multivariate cases, but essential for functional where the scaling may be atypical.

In implementing, make sure to treat edge cases: 

- Single experiment and/or single configuration, including where the data value is near zero
- Cases with (near) zero variance

**Comment by briadam** [comment]
Related to this is that if any scaling takes place internally, any client would still interact with the various classes in the original unscaled space.  For instance, if I query an API or examine a file for a chain, it would be in the same space presented to the solver, if I ask for a GP prediction at a new point g(theta, x), I'd get back something comparable to the original simulation response space, not some standardized space.

**Comment by dmcdougall** [comment]
Domain scaling done in #566.

**Comment by dmcdougall** [comment]
Data scaling done in #602.
