### ISSUE TITLE
Single quotes break Boost program options

### ISSUE THREAD

**Issue by briadam** [libqueso/queso#642]
On the dev branch, using single quotes around booleans, strings, and sets breaks input file parsing when using Boost program options.  This is counter to the input file changes of @dmcdougall in #457  See the discussion in #640, where @roystgnr asserts that reverting #457 is likely okay.  

Specifically these tests break:
- FAIL: test_BoostInputOptionsParser
- FAIL: test_intercomm0/test_intercomm0_gravity_run.sh
- FAIL: t01_valid_cycle/rtest01.sh
- FAIL: test_mala

**Comment by dmcdougall** [comment]
Does removing the quotes produce a file that is acceptable by both BPO and GetPot?

**Comment by briadam** [comment]
Resolved by #644
